# Generated by Django 4.0.2 on 2022-02-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_user_alter_transaction_discripton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='discripton',
            new_name='discription',
        ),
    ]
